Repository Team-DevHub/dev-hub-back, pull requests merged in 2024-07, with the labels that each got.

#46 [Feat/#45]: 스크랩 API 구현
  app.js
  controllers/authController.js
  controllers/commentController.js
  controllers/postController.js
  controllers/scrapController.js
  controllers/usersController.js
  queries/scrapQuery.js
  routes/authRouter.js
  routes/commentRouter.js
  routes/postRouter.js
  routes/scrapRouter.js
  routes/usersRouter.js
  services/postService.js
  services/scrapService.js
  utils/tokenHandler.js
Labels: feat

#48 [Chore/#47]: 배포용 yaml 추가
  .github/workflows/deploy.yaml
Labels: chore

#51 [Fix/#50]: 스크랩 리스트 조회 API 오류 수정
  services/scrapService.js
Labels: fix

#52 [Feat/#44]: 구글 로그인 구현
  constants/url.js
  controllers/authController.js
  queries/authQuery.js
  routes/authRouter.js
  services/authService.js
Labels: feat

#54 [Feat/#53]: Google 로그인 계정 해지(탈퇴)
  constants/url.js
  controllers/authController.js
  controllers/usersController.js
  routes/authRouter.js
  services/authService.js
Labels: feat

#57 [Fix/#56]: 게시글 상세 조회 > 스크랩 여부 오류 수정
  controllers/postController.js
  queries/scrapQuery.js
  services/postService.js
Labels: fix

#59 [Feat/#58]: 토큰 재발급 API 구현
  controllers/usersController.js
  queries/userQuery.js
  routes/usersRouter.js
  services/authService.js
  services/userService.js
  utils/verifyToken.js
Labels: feat

#61 [Fix/#60]: 멘토링 피드백 반영
  app.js
  controllers/postController.js
  controllers/scrapController.js
  queries/postQuery.js
  queries/scrapQuery.js
  routes/postRouter.js
  routes/scrapRouter.js
  services/postService.js
  services/scrapService.js
Labels: fix

#63 [Fix/#62]: 토큰 재발급 API 수정
  controllers/usersController.js
  routes/usersRouter.js
  utils/verifyToken.js
Labels: fix

#64 [Fix/#55]: Google 회원 탈퇴 오류 수정
  controllers/authController.js
  queries/authQuery.js
  services/authService.js
Labels: fix

#66 [Fix/#65]: Google 로그인 탈퇴 로직 수정
  queries/authQuery.js
  services/authService.js
Labels: fix
